version: 2

defaults: &defaults
  working_directory: ~/qlik-network-chart
  docker:
    - image: circleci/node:stretch
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "network-vis-chart"
    PACKAGE_NAME: "qlik-network-chart"

jobs:
  test:
    docker:
    - image: circleci/node:stretch-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: BlackDuck scan
          command: curl -s https://detect.synopsys.com/detect.sh | bash -s -- \
            --blackduck.url="https://qliktech.blackducksoftware.com" \
            --blackduck.trust.cert=true \
            --blackduck.username="svc-blackduck" \
            --blackduck.password=${svc_blackduck} \
            --detect.project.name="viz-bundle-qlik-network-chart"

  bump-version:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Bump version
          command: scripts/bump-version.sh $GITHUB_ORG $GITHUB_REPO
      - persist_to_workspace:
          root: ~/qlik-network-chart
          paths:
            - BUMPED_VERSION

  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-network-chart
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build and package
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            yarn build:zip
            sudo chmod +x scripts/verify-files.sh
            scripts/verify-files.sh
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/qlik-network-chart
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-network-chart
      - run:
          name: Install ghr
          command: scripts/install-ghr.sh
      - run:
          name: Create GitHub Release
          command: |
            export VERSION=$(scripts/get-bumped-version.sh)
            echo "Version: ${VERSION}"
            scripts/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME $VERSION

workflows:
  version: 2
  master_flow:
    jobs:
      - test
      - bump-version:
          requires:
            - test
      - build:
          requires:
            - bump-version
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
